feat: scheduled root propagation mechanism
kfastov/worldcoin-bridge-linea pull request #49
Opened 2024-08-24 17:26 UTC by TropicalDog17

2024-08-27 11:03 UTC, kfastov requested changes
Looks legitimate, just remove the fs dependency and check if we should increase gas on the unpredictable gas error (I can be wrong at it) and we can finish with it.

2024-08-31 01:59 UTC, TropicalDog17 commented on scripts/LineaRootPropagator.js
> +        if (error.code === 'UNPREDICTABLE_GAS_LIMIT' || error.message.includes('transaction underpriced')) {
yeah I think I misunderstand this error, I have adjusted, please check @kfastov

2024-08-31 10:41 UTC, kfastov commented
Thank you!

2024-08-31 10:42 UTC, kfastov approved these changes
I like how this PR is made

2024-08-31 10:42 UTC, merged